name: Generate Dockerfiles

on:
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ROBO_PR_APP_ID }}
          private-key: ${{ secrets.ROBO_PR_CLIENT_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies with uv
        run: |
          uv sync --all-extras --dev

      - name: Run generate_dockerfiles.py
        run: uv run generate_dockerfiles.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Dockerfiles
          title: 'Update Dockerfiles'
          body: |
            This PR updates the Dockerfiles in the `docker/` directory.
            
            Generated automatically by the Generate Dockerfiles workflow.
          branch: autopr-update-dockerfiles
          delete-branch: true
          base: master
          labels: |
            automated pr
            dockerfiles
